### ISSUE TITLE
-pc issue?

### ISSUE THREAD

**Issue by jpesicek** [Jose-Alvarez/FMC#4]
[jap_select3.txt](https://github.com/Jose-Alvarez/FMC/files/3188143/jap_select3.txt)

Hi, with last issue fixed, I now tried your original test to color symbols by ID and get errors. If I can get this to work, I can stop bothering you ;)  many thanks. 

FMC.py -p 'jap_select3.png' jap_select3.txt -pc ID
#Longitude Latitude Depth_(km) mrr mtt mff mrt mrf mtf Exponent_(dyn-cm) X_position(GMT) Y_position(GMT) ID Rupture_type
149.27 44.12 28.0 1.01 -0.47 -0.54 1.68 1.85 -0.48 27.0 X Y r R
138.87 40.44 13.0 3.96 -0.85 -3.11 -1.01 -2.5 -0.81 27.0 X Y b R
143.08 39.95 24.0 0.61 -0.07 -0.55 0.56 1.1 -0.11 27.0 X Y g R
139.28 42.71 16.0 4.52 -0.29 -4.23 0.04 -1.58 0.02 27.0 X Y g R
142.99 40.56 28.0 1.73 0.13 -1.87 1.78 4.16 -0.43 27.0 X Y g R
150.17 44.82 26.0 3.11 -1.39 -1.72 4.87 5.79 -1.87 27.0 X Y r R
143.84 42.21 28.0 0.78 -0.41 -0.37 1.32 2.59 -0.66 28.0 X Y b R
137.0 32.94 16.0 6.7 -8.3 1.6 2.0 0.6 0.1 26.0 X Y g R
137.22 33.13 12.0 1.11 -1.77 0.66 -0.01 0.11 0.04 27.0 X Y b R
154.33 46.71 14.0 1.74 -0.56 -1.18 1.64 2.58 -0.77 28.0 X Y r R
154.8 46.17 12.0 -1.38 1.33 0.05 -0.27 -0.78 0.8 28.0 X Y g N-SS
142.78 38.56 14.0 0.49 -0.02 -0.47 0.42 1.05 -0.13 27.0 X Y g R
143.05 37.52 20.0 1.73 -0.28 -1.45 2.12 4.55 -0.66 29.0 X Y b R
141.38 35.92 29.0 4.39 -0.31 -4.07 3.17 6.34 -1.97 27.0 X Y r R
144.63 38.27 21.0 -3.03 0.03 3.0 -0.41 -0.34 0.47 27.0 X Y r N
143.83 37.77 20.0 -6.5 -1.2 7.6 0.4 1.2 3.1 26.0 X Y b N
Traceback (most recent call last):
  File "./FMC.py", line 849, in <module>
    gridspacing)
  File "/Users/jpesicek/Dropbox/sw/FMC-master/plotFMC.py", line 186, in circles
    cbar = plt.colorbar(sc, shrink=0.5)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2100, in colorbar
    ret = gcf().colorbar(mappable, cax = cax, ax=ax, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/figure.py", line 2129, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/colorbar.py", line 1566, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/colorbar.py", line 1072, in __init__
    mappable.autoscale_None()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/cm.py", line 374, in autoscale_None
    raise TypeError('You must first set_array for mappable')
TypeError: You must first set_array for mappable

**Comment by Jose-Alvarez** [comment]
Hi Jeremy,

The problem here is that when shading the symbols matplotlib expects or rgb triplets, hsv values, cmyk, etc... or numbers that can be mapped in a gradient colormap built as a continuous function from the minimum value to the maximum of the selected field. If you are using as event ID strings python complains because he can't assign positions to strings in a colormap.

When using numbers as IDs FMC works fine.

Maybe I can include a warning if the selected field for the symbol color is not a numeric value.

**Comment by jpesicek** [comment]
Hi, thanks for responding.  I have tried using numbers as well and still get errors, although they are different errors.  Would it be possible to post an example data file that works for you? I've tried editing the IDs in several ways and cannot get it to work.  thanks

**Comment by Jose-Alvarez** [comment]
Hi Jeremy

As example I am using the "jap_select.dat" input file and substituting the ID with the row number with awk. The result is the expected and a figure with the shading of the circle as a function of the row ID is produced. I attach the code and the result. Please try to replicate it and send me the errors.

code:
`awk '{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NR}' jap_select.dat | FMC.py -p 'jap_select3.png' -pc ID`

![jap_select3](https://user-images.githubusercontent.com/34281458/57985406-e85add80-7a67-11e9-989b-7d6df7290bd5.png)

**Comment by jpesicek** [comment]
$ awk '{print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NR}' jap_select.dat | FMC.py -p 'jap_select3.png' -pc ID
#Longitude Latitude Depth_(km) mrr mtt mff mrt mrf mtf Exponent_(dyn-cm) X_position(GMT) Y_position(GMT) ID Rupture_type
149.27 44.12 28.0 1.01 -0.47 -0.54 1.68 1.85 -0.48 27.0 X Y 1 R
138.87 40.44 13.0 3.96 -0.85 -3.11 -1.01 -2.5 -0.81 27.0 X Y 2 R
143.08 39.95 24.0 0.61 -0.07 -0.55 0.56 1.1 -0.11 27.0 X Y 3 R
139.28 42.71 16.0 4.52 -0.29 -4.23 0.04 -1.58 0.02 27.0 X Y 4 R
142.99 40.56 28.0 1.73 0.13 -1.87 1.78 4.16 -0.43 27.0 X Y 5 R
150.17 44.82 26.0 3.11 -1.39 -1.72 4.87 5.79 -1.87 27.0 X Y 6 R
143.84 42.21 28.0 0.78 -0.41 -0.37 1.32 2.59 -0.66 28.0 X Y 7 R
137.0 32.94 16.0 6.7 -8.3 1.6 2.0 0.6 0.1 26.0 X Y 8 R
137.22 33.13 12.0 1.11 -1.77 0.66 -0.01 0.11 0.04 27.0 X Y 9 R
154.33 46.71 14.0 1.74 -0.56 -1.18 1.64 2.58 -0.77 28.0 X Y 10 R
154.8 46.17 12.0 -1.38 1.33 0.05 -0.27 -0.78 0.8 28.0 X Y 11 N-SS
142.78 38.56 14.0 0.49 -0.02 -0.47 0.42 1.05 -0.13 27.0 X Y 12 R
143.05 37.52 20.0 1.73 -0.28 -1.45 2.12 4.55 -0.66 29.0 X Y 13 R
141.38 35.92 29.0 4.39 -0.31 -4.07 3.17 6.34 -1.97 27.0 X Y 14 R
144.63 38.27 21.0 -3.03 0.03 3.0 -0.41 -0.34 0.47 27.0 X Y 15 N
143.83 37.77 20.0 -6.5 -1.2 7.6 0.4 1.2 3.1 26.0 X Y 16 N
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/colors.py", line 174, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
KeyError: (1, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4232, in scatter
    colors = mcolors.to_rgba_array(c)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/colors.py", line 275, in to_rgba_array
    result[i] = to_rgba(cc, alpha)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/colors.py", line 176, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/colors.py", line 227, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./FMC.py", line 849, in <module>
    gridspacing)
  File "/Users/jpesicek/Dropbox/sw/FMC-master/plotFMC.py", line 185, in circles
    cmap='plasma_r')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2862, in scatter
    is not None else {}), **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4245, in scatter
    .format(nc=n_elem, xs=x.size, ys=y.size)
ValueError: 'c' argument has 16 elements, which is not acceptable for use with 'x' with size 16, 'y' with size 16.

**Comment by Jose-Alvarez** [comment]
Dear Jeremy

Sorry for the late, late answer... I don't know why, but I didn't receive the notification of your comment.

I am unable to reproduce your exceptions, although my Python version is 3.5 instead of 3.7. It could be a problem with matplotlib. 

Could you please tell me which version of matplotlib is running on your system?

**Comment by jpesicek** [comment]
no problem, thanks for the help.  I am using matplotlib 3.0.3

**Comment by Jose-Alvarez** [comment]
Ok, this bug is also affecting to other users with **matplotlib version 3** and I have been finally able to reproduce the error.

A change in the matplotlib color module is raising this error due to the way matplotlib is handling arrays as input to produce colormaps.
